apiVersion: v1
kind: Service
metadata:
  name: g73-production-api-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: g73-production-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30005
  type: LoadBalancer