name: pipeline payment-ms

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Para obter o histórico completo do git

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install Go dependencies
        run: go mod download

      - name: Run tests and generate coverage report
        run: |
          mkdir -p coverage
          go test ./... -coverprofile=coverage/coverage.out
          go tool cover -html=coverage/coverage.out -o coverage/coverage.html

      - name: Install gocover-cobertura
        run: go install github.com/t-yuki/gocover-cobertura@latest
  
      - name: Convert coverage report to Cobertura format
        run: |
            mkdir -p coverage
            $HOME/go/bin/gocover-cobertura < coverage/coverage.out > coverage/coverage.xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage

  code-analisys: 
    runs-on: ubuntu-latest
    needs: test-unit
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
              
        - name: Download coverage report
          uses: actions/download-artifact@v3
          with:
            name: code-coverage-report
            path: coverage
        
        - name: List coverage directory
          run: ls -la coverage

        - name: Display coverage XML
          run: cat coverage/coverage.xml      

        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: code-analisys
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Docker image
        run: |
          docker build -t igorramos/g73-techchallenge-payment .
          docker push igorramos/g73-techchallenge-payment      



